core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path 
import ticketing.routing
from ticketing import routing as ticketing_routing
from django.conf import settings
from django.conf.urls.static import static
# from core.routing import urlpatterns as core_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register
    path("", include("apps.home.urls"))  ,
    # UI Kits Html files
      # path('ws/', include(ticketing.routing.websocket_urlpatterns)),
    #   path('core/', include(core_urlpatterns)),
     path('ticketing/', include('ticketing.urls')),
      path('ticketing/', include(('ticketing.urls', 'ticketing'), namespace='ticketing')),
    path('ticketing/', include(ticketing_routing.websocket_urlpatterns)),
   

     
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "Telecel Ticketing App Administration Page"
admin.site.site_title = "Admin Page"
admin.site.index_title = "Welcome to the Admin Page"

ticketing/urls.py
from django.urls import path



from . import views

# app_name = 'ticketing'
  
urlpatterns = [
path('add_ticket/', views.add_ticket, name='add_ticket'),
path('accept_ticket/<int:pk>/', views.accept_ticket, name='accept_ticket'),
path('all_ticket_created/', views.all_ticket_created, name='all_ticket_created'),
# path('ticket_to_claim_cs/', views.ticket_to_claim_cs, name="ticket_to_claim_cs"),
# path('ticket_intergration_cs/', views.ticket_intergration_cs, name="ticket_intergration_cs"),
path('ticket_queue/', views.ticket_queue, name="ticket_queue"),
path('update_ticket/<int:pk>', views.update_ticket, name="update_ticket"),
# path('technicain_feedback/<int:pk>', views.technicain_feedback, name='technicain_feedback'),
path('ticket_details/<int:pk>/', views.ticket_details, name='ticket_details'),
# path('postpone_ticket/<int:pk>', views.postpone_ticket, name="postpone_ticket"),
path('complete_ticket_customer/<int:pk>/', views.complete_ticket_customer, name="complete_ticket_customer"),
path('close_ticket/<int:pk>', views.close_ticket, name="close_ticket"),
path('ticket_in_progress/', views.ticket_in_progress, name="ticket_in_progress"),
# path('all_ticket_created_tech/', views.all_ticket_created_tech, name='all_ticket_created_tech'),
path('ticket_to_claim_tech/', views.ticket_to_claim_tech, name='ticket_to_claim_tech'),
path('ticket_report/', views.ticket_report, name="ticket_report"),
# path('ticket_intergration/', views.ticket_intergration, name="ticket_intergration"),
path('customer_approve/<int:pk>/', views.customer_approve, name="customer_approve"),
path('complete_ticket/<int:pk>/', views.complete_ticket, name="complete_ticket"),
# # path('delete_ticket/<int:pk>/', views.delete_ticket, name="delete_ticket"),
path('ticket_completed/', views.ticket_completed, name="ticket_completed"),
# path('export_csv_filter/', views.export_csv_filter, name="export_csv_filter"),
# path('export_pdf_filter/', views.export_pdf_filter, name="export_pdf_filter"),
 path('download/<path:attachment_url>/', views.download_attachment, name='download_attachment'),
 path('technician_complete_ticket/', views.technician_complete_ticket, name="technician_complete_ticket"),
 path('reject_ticket_form/<int:pk>/', views.reject_ticket_form, name='reject_ticket_form'),
 path('user_activity_log/', views.user_activity_log, name="user_activity_log"),
path('technician_complete_ticket_admin/', views.technician_complete_ticket_admin, name="technician_complete_ticket_admin"),
path('user_activities/', views.user_activities_view, name='user_activities'),
path('customer_queue/', views.customer_queue, name='customer_queue'),


path('send_email/', views.send_email, name='send_email'),

path('api/create_ticket/', views.create_ticket_api, name='create_ticket_api'),






    
 ]

apps/templates/includes/footer-fullscreen.html
<style>
  .footer-class {
    background: #ffffff;
}

.footer-link {
  color: #C80D0D !important;
  text-decoration: none;
  background-color: transparent;
}
</style>
    <footer class="py-5 footer-class">
      <div class="container">
        <div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="copyright text-center text-xl-left  text-danger">
              <a href="https://teleceliberia.com/" 
              class="font-weight-bold ml-1" target="_blank">More Info</a>
            </div>
          </div>
          <div class="col-xl-6">
            <div class="text-center text-xl-right  text-info">
               &copy; <a class="footer-link" href="https://teleceliberia.com/" 
               class="font-weight-bold ml-1" target="_blank">  Telecel Liberia</a> 
            </div>
          </div>
        </div>
      </div>
    </footer>

apps/templates/includes/footer.html
<style>
  .footer-class {
    background: #ffffff;
}

.footer-link {
  color: #C80D0D !important;
  text-decoration: none;
  background-color: transparent;
}
</style>
      <!-- Footer -->
      <footer class="footer">
        <div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="text-center text-xl-left  text-info">
              <a href="https://teleceliberia.com/" 
                 class="font-weight-bold ml-1" target="_blank">More Info</a>
            </div>
          </div>
          <div class="col-xl-6">
            <div class="text-center text-xl-right text-danger">
              <a class="footer-link" href="https://teleceliberia.com/" 
                 class="font-weight-bold ml-1" target="_blank"> Telecel Liberia</a> 
                
            </div>
          </div>
        </div>
      </footer>

apps/templates/includes/navigation-fullscreen.html
<style>
  .logo-img{
    width: 55px;
    height: 600px;
  }

  .logo-img-cont{
    width: 100px;
    height: 700px;
  }
</style>
<nav id="navbar-main" class="navbar navbar-horizontal navbar-transparent navbar-main navbar-expand-lg navbar-light">
  <div class="container">
    <a class="navbar-brand" href="/" class="logo-img-cont">
      {% comment %} <img src="/static/assets/img/brand/Telecel-Liberia-Logo-Open-File-white-1.png" alt=" Logo." class="logo-img"> {% endcomment %}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse navbar-custom-collapse collapse" id="navbar-collapse">
      <div class="navbar-collapse-header">
        <div class="row">
          <div class="col-6 collapse-brand">
            <a href="/">
              <img src="/static/assets/img/brand/logotel.jpeg">
            </a>
          </div>
          <div class="col-6 collapse-close">
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
              <span></span>
              <span></span>
            </button>
          </div>
        </div>
      </div>
      <ul class="navbar-nav mr-auto">
    
      </ul>
    </div>
  </div>
</nav>

apps/templates/includes/navigation.html
<style>
  .count-badge {
    position: absolute;
    top: -10px;
    right: -10px;
    background-color: red;
    color: white;
    font-size: 14px;
    padding: 4px;
    border-radius: 50%;
  }

  @keyframes blink {
    0% {
      opacity: 1;
    }
    50% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
  
  .blinking {
    animation: blink 1s infinite;
  }

  .list-group {
    display: flex;
    flex-direction: column;
    padding-left: 0;
    margin-bottom: 0;
    width: 100%;
}
  
.bg-danger {
   background-color: #C80D0D !important;
}
  
.profile-photo {
  width: 30px;
  height: 35px;
}

</style>
<nav class="navbar navbar-top navbar-expand navbar-dark bg-danger border-bottom">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Search form -->
      <form class="navbar-search navbar-search-light form-inline mr-sm-3" id="navbar-search-main">
        <div class="form-group mb-0">
          <div class="input-group input-group-alternative input-group-merge">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-search"></i></span>
            </div>
            <input class="form-control" placeholder="Search" type="text">
          </div>
        </div>
        <button type="button" class="close" data-action="search-close" data-target="#navbar-search-main" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </form>
      <!-- Navbar links -->
      <ul class="navbar-nav align-items-center  ml-md-auto ">
        <li class="nav-item d-xl-none">
          <!-- Sidenav toggler -->
          <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </div>
        </li>
        <li class="nav-item d-sm-none">
          <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
            <i class="ni ni-zoom-split-in"></i>
          </a>
        </li>
        <li class="nav-item dropdown">
          {% if request.user.is_technician %}
          <a  class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="ni ni-bell-55 {% if ticketPendingtech.count > 0 %}blinking{% endif %}">
              <span class="count-badge">{{ ticketPendingtech.count }}</span>
            </i>
            
          </a>
          

          {% elif request.user.is_customer_care %}

          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="ni ni-bell-55 {% if ticketunassigned.count > 0 %}blinking{% endif %}">
              <span class="count-badge">{{ ticketunassigned.count }}</span>
            </i>
          </a>

          {% endif %}
          
          
          <div class="dropdown-menu dropdown-menu-xl  dropdown-menu-right  py-0 overflow-hidden">
            <!-- Dropdown header -->
            <div class="px-3 py-3">
              {% if request.user.is_technician %}
              <h6 class="text-sm text-muted m-0">You have <strong class="text-primary">{{ticketPendingtech.count}}</strong> ticket Pending.</h6>
              {% elif request.user.is_customer_care %}
              <h6 class="text-sm text-muted m-0">You have <strong class="text-primary">{{ticketunassigned.count}}</strong> unassigned tickets.</h6>
              {% endif %}
            </div>

            <!-- List group -->
           
            <div class="list-group list-group-flush">
              {% if request.user.is_technician %}

              {% for tickets in ticketPendingtech %}
             
             
              
              <a href="{% url 'ticket_queue' %}" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                    <img alt="Image placeholder" src="/static/assets/img/brand/female-Avatar.png" class="avatar rounded-circle">
                  </div>
                  <div class="col ml--2">
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <h4 class="mb-0 text-sm">{{tickets.created_by}}</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>{{tickets.date_created}}</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">{{tickets.title}}</p>
                  </div>
                  
                </div>
                {% endfor %}
                
              </a>
              
             
             
             
            </div>
           
            <a href="{% url 'ticket_queue' %}" class="dropdown-item text-center text-primary font-weight-bold py-3">View all</a>
          </div>


          {% else %}
          <div class="list-group list-group-flush">
            {% for tickets in ticketunassignedFive %}
           
           
            
            <a href="{% url 'all_ticket_created' %}" class="list-group-item list-group-item-action">
              <div class="row align-items-center">
                <div class="col-auto">
                  <!-- Avatar -->
                  <img alt="Image placeholder" src="/static/assets/img/brand/female-Avatar.png" class="avatar rounded-circle">
                </div>
                <div class="col ml--2">
                  <div class="d-flex justify-content-between align-items-center">
                    <div>
                      <h4 class="mb-0 text-sm">{{tickets.customer}}</h4>
                    </div>
                    <div class="text-right text-muted">
                      <small>{{tickets.date_created}}</small>
                    </div>
                  </div>
                  <p class="text-sm mb-0">{{tickets.title}}</p>
                </div>
                
              </div>
              {% endfor %}
              
            </a>
            
           
           
           
          </div>
         
          <a href="{% url 'all_ticket_created' %}" class="dropdown-item text-center text-primary font-weight-bold py-3">View all</a>
        </div>


          {% endif %}
          
          
        </li>


        {% if not request.user.is_employe and not request.user.is_supervisor %}

        <li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="notification-icon">
            <i id="notification-count" class="ni ni-ungroup" style="position: relative;">
              {% if notification_count > 0 %}
                <span style="position: absolute; top: -10px; right: -10px; background-color: red; color: white; border-radius: 50%; padding: 4px 6px; font-size: 12px;">
                  {{ notification_count }}
                </span>
              {% endif %}
            </i>
            
          </a>
          
          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-dark bg-default dropdown-menu-right">
            <div class="row shortcuts px-4">
              <!-- Dropdown header -->
              <div class="px-3 py-3">
                <h6 class="text-sm text-muted m-0">You have <strong class="text-primary" id="notification-count">{{ notification_count }}</strong> notifications.</h6>
              </div>
              <!-- List group -->
              <div class="list-group list-group-flush" id="notification-list">
                {% for message in chat_messages %}
                  <a href="{% url 'ticketing:ticket_details' message.ticket.pk %}" class="list-group-item list-group-item-action">
                    <div class="row align-items-center">
                      <div class="col-auto">
                        <!-- Avatar -->
                        <img alt="Image placeholder" src="/static/assets/img/theme/team-1.jpg" class="avatar rounded-circle">
                      </div>
                      <div class="col ml--2">
                        <div class="d-flex justify-content-between align-items-center">
                          <div>
                            <h4 class="mb-0 text-sm">{{ message.sender }}</h4>
                          </div>
                          <div class="text-right text-muted">
                            <small>{{ message.timestamp|date:"M d, Y g:iA" }}</small>
                          </div>
                        </div>
                        <p class="text-sm mb-0">{{ message.message|safe }}</p>
                        {% if message.attachment_url %}
                          <p class="text-sm mb-0">{{ message.sender }} sent an attachment</p>
                        {% endif %}
                      </div>
                    </div>
                  </a>
                {% endfor %}
              </div>
            </div>
          </div>
        </li>

        {% endif%}



      </ul>
      <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
        <li class="nav-item dropdown">
          <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="media align-items-center">
            
              <span class="avatar avatar-sm rounded-circle">
                <img class="profile-photo" alt="Image placeholder" src="{% if user.profile_photo %}{{ user.profile_photo.url }}{% else %}/static/assets/img/brand/Female-Avatar.png{% endif %}">
            </span>
            
            
             
              <div class="media-body  ml-2  d-none d-lg-block">
                <span class="mb-0 text-sm  font-weight-bold">
                  {{ request.user.username }}
                </span>
              </div>
            </div>
          </a>
          <div class="dropdown-menu  dropdown-menu-right ">
            <div class="dropdown-header noti-title">
              <h6 class="text-overflow m-0">Welcome!</h6>
            </div>
            <a href="{% url 'user_profile' %}" class="dropdown-item">
           
              <i class="ni ni-single-02"></i>
              <span>My profile</span>
            </a>

            <a href="{% url 'change_password' %}" class="dropdown-item">
           
              <i class="ni ni-lock-circle-open"></i>
              <span>Change Password</span>
            </a>
            
            <div class="dropdown-divider"></div>
            <a href="{% url 'logout' %}" class="dropdown-item">
              <i class="ni ni-user-run text-red"></i>
              <span>Logout</span>
            </a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>



<script>
  var notificationIcon = document.getElementById('notification-icon');
  var notificationList = document.getElementById('notification-list');
  var notificationCount = document.getElementById('notification-count');

 
  notificationList.style.display = 'none';

 
  notificationIcon.addEventListener('click', function(event) {
    event.preventDefault();
    if (notificationList.style.display === 'none') {
      notificationList.style.display = 'block';
      notificationCount.textContent = '0'; 
    } else {
      notificationList.style.display = 'none';
       
    }
  });
</script>

apps/templates/includes/scripts.html
  <script src="/static/assets/vendor/jquery/dist/jquery.min.js"></script>
  <script src="/static/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="/static/assets/vendor/js-cookie/js.cookie.js"></script>
  <script src="/static/assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js"></script>
  <script src="/static/assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js"></script>
  
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4.2.1/dist/chart.umd.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>


  